# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserInfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'UserInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eUserInfo.proto\x12\x06signup\"\x84\x01\n\x04User\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x0cmobileNumber\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x11\n\tfirstName\x18\x05 \x01(\t\x12\x10\n\x08lastName\x18\x06 \x01(\t\x12\x10\n\x08password\x18\x07 \x01(\t\"M\n\x13TransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nkafkaTopic\x18\x02 \x01(\t\x12\x11\n\tpartition\x18\x03 \x01(\x05\x32@\n\x08UserInfo\x12\x34\n\x07\x61\x64\x64User\x12\x0c.signup.User\x1a\x1b.signup.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=159
  _globals['_TRANSACTIONRESPONSE']._serialized_start=161
  _globals['_TRANSACTIONRESPONSE']._serialized_end=238
  _globals['_USERINFO']._serialized_start=240
  _globals['_USERINFO']._serialized_end=304
# @@protoc_insertion_point(module_scope)
