FROM debezium/connect:2.7.3.Final
USER root
WORKDIR /kafka/.

COPY ./connector-config ./connector-config

# Downloading protobuf-converter
RUN curl -L -o ./libs/protobuf-converter.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-connect-protobuf-converter/7.7.3/kafka-connect-protobuf-converter-7.7.3.jar

# Downloading SchemaRegistry client
RUN curl -L -o ./libs/schema-registry-client.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.4.0/kafka-schema-registry-client-7.4.0.jar

# Downloading Schema Registry (might get rid of)
RUN curl -L -o ./libs/schema-registry.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-schema-registry/7.4.0/kafka-schema-registry-7.4.0.jar

# Downloading Schema Serializer
RUN curl -L -o ./libs/schema-serializer.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.4.0/kafka-schema-serializer-7.4.0.jar

# Protobuf provider
RUN curl -L -o ./libs/protobuf-provider.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-protobuf-provider/7.4.0/kafka-protobuf-provider-7.4.0.jar
    
# Google Guava 
RUN curl -L -o ./libs/google-guava.jar \
    https://repo1.maven.org/maven2/com/google/guava/guava/33.4.0-jre/guava-33.4.0-jre.jar

# Protobuf Serializer 
RUN curl -L -o ./libs/protobuf-serializer.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-protobuf-serializer/7.4.0/kafka-protobuf-serializer-7.4.0.jar

# Schema Converter  
RUN curl -L -o ./libs/schema-converter.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-schema-converter/7.4.0/kafka-schema-converter-7.4.0.jar



# ENTRYPOINT ./connector-config/init-config.sh & /docker-entrypoint.sh start
ENTRYPOINT /kafka/connector-config/init-config.sh & /docker-entrypoint.sh start